Fix build with GCC on 32bit x86
GCC defines macro `i386` on x86[1]. This causes following compiler
errors:

	Scanning dependencies of target win32pe
	[ 11%] Building CXX object win32pe/CMakeFiles/win32pe.dir/src/file.cpp.o
	/root/win32pe/win32pe/include/win32pe/fileheader.h:45:9: error: expected identifier before numeric constant
	         i386  = 0x014c,
	         ^
	/root/win32pe/win32pe/include/win32pe/fileheader.h:45:9: error: expected ‘}’ before numeric constant
	/root/win32pe/win32pe/include/win32pe/fileheader.h:45:9: error: expected unqualified-id before numeric constant

[1] https://sourceforge.net/p/predef/wiki/Architectures/